version: "2"
services:
  mongodb:
    image: mongo:3.4.7
    hostname: mongodb
    container_name: mongodb
    expose:
      - "27017"
    ports:
      - "27018:27017"
    volumes:
      - mongodb-volume:/data
    command: mongod --smallfiles

  orion:
    image: fiware/orion:1.7.0
    hostname: orion
    container_name: orion
    links:
      - mongodb
    expose:
      - "1026"
    ports:
      - "1026:1026"
    command: -dbhost mongodb

  mosquitto:
    image: ansi/mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
    ports:
      - "1883:1883"

  idas:
    image: fiware/iotagent-ul:1.3.0
    hostname: idas
    container_name: idas
    volumes:
      - ./config/idas/config-blank.js:/opt/iotaul/config-blank.js
    links:
      - mongodb:mongo
      - orion
      - mosquitto
    expose:
      - "7896"
      - "4041"
    ports:
      - "7896:7896"
      - "4041:4041"

  cygnus:
    image: fiware/cygnus-ngsi:1.7.1
    hostname: cygnus
    container_name: cygnus
    volumes:
      - ./config/cygnus/agent.conf:/opt/apache-flume/conf/agent.conf
    links:
      - mysql-cygnus:mysql-cygnus
      - mongodb-cygnus:mongodb-cygnus
    expose:
      - "5050"
    ports:
      - "5050:5050"
    environment:
      - CYGNUS_MYSQL_HOST=mysql-cygnus
      - CYGNUS_MYSQL_PORT=3306
      - CYGNUS_MYSQL_USER=root
      - CYGNUS_MYSQL_PASS=YOUR_MYSQL_ROOT_PASSWORD
      - CYGNUS_MONGO_HOSTS=mongodb-cygnus:27017
      - CYGNUS_MONGO_USER=YOUR_MONGODB_USER
      - CYGNUS_MONGO_PASS=YOUR_MONGODB_PASSWORD
      - CYGNUS_LOG_LEVEL=INFO

  mysql-cygnus:
    image: mysql:5.7
    hostname: mysql-cygnus
    container_name: mysql-cygnus
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=YOUR_MYSQL_ROOT_PASSWORD
    volumes:
      - mysql-cygnus-volume:/var/lib/mysql

  mongodb-cygnus:
    image: mongo:3.4.7
    hostname: mongodb-cygnus
    container_name: mongodb-cygnus
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - mongodb-cygnus-volume:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=YOUR_MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=YOUR_MONGODB_PASSWORD
    command: mongod --smallfiles

  sth-comet:
    image: telefonicaiot/fiware-sth-comet:2.2.0
    hostname: sth-comet
    container_name: sth-comet
    volumes:
      - ./config/sth/config.js:/opt/sth/config.js
    links:
      - mongodb-cygnus
    expose:
      - "8666"
    ports:
      - "8666:8666"

volumes:
  mongodb-volume:
  mysql-cygnus-volume:
  mongodb-cygnus-volume:
